sigstore/sigstore-conformance

action.py

I noticed this when trying to add a conformance testing workflow to `sigstore-python`. Since we're no longer executing the action from the same directory as the `GITHUB_ACTION_PATH`, it doesn't know where `test/` is.

action.py: Specify absolute path in `pytest` invocation

---

docs/cli_protocol.md

Specifies bundle creation and consumption standards by:
- adding `sign-bundle` and `verify-bundle` subcommands;
- adding the `--bundle` flag that specifies the bundle to output or verify from.
I'm unsure of if we want to have separate `sign-bundle` and `verify-bundle` subcommands, as I mentioned in https://github.com/sigstore/sigstore-conformance/issues/65#issuecomment-1513638198. I can remove these subcommands and make some flags optional if we feel that approach is better.
Resolves #51.

Bundle creation and consumption specs

---

.github/workflows/ci.yml
.github/workflows/conformance.yml

The changeset for #65 depends on Python 3.8 features, which causes issues with the CI workflow pinned on 3.7: https://github.com/trail-of-forks/sigstore-conformance/actions/runs/4747768731/jobs/8433107457
To fix that issue, this changeset pins both the conformance testing workflow and the CI workflow to a consistent version of Python.

workflows: pin python version to 3.11

---

.github/workflows/oidc.yml

My plan is to get this in first. And then once we have tokens being generated continuously, I'll be able to develop/test against these tokens.

workflows: Add OIDC token generation workflow

---

docs/cli_protocol.md
sigstore-python-conformance
test/client.py
test/conftest.py
test/test_certificate_verify.py
test/test_signature_verify.py
test/test_simple.py

Adapts existing tests to cover the bundle flow (empty materials, mismatched materials, ...) To this effect, extends `SigstoreClient` to support the `*-bundle` subcommands.
Depends on #51.
Resolves #65.

Basic bundle tests

---

.github/workflows/conformance.yml
test/conftest.py

I see we have this fixed in https://github.com/sigstore/sigstore-conformance/pull/78 but we need to get this in now as it's disrupting other PRs from Dependabot.
I've also switched away from `pull_request_target` since we're no longer using ambient credentials.

conftest: Add `--identity-token` option back

---

.github/workflows/conformance.yml
action.py
action.yml
requirements.txt
sigstore-python-conformance
test/client.py
test/test_bundle.py
test/test_certificate_verify.py
test/test_signature_verify.py

This shaves down a few of the layers of indirection in the conformance suite, which will (hopefully) make error messages easier to sift through in the future.
Closes #88.

action: invoke pytest through python

---

.github/workflows/conformance.yml
Makefile
action.py
action.yml
dev-requirements.txt
pyproject.toml
sigstore-python-conformance
test/client.py
test/conftest.py
test/test_bundle.py
test/test_signature_verify.py

This adds an `xfail` input that configures a whitespace-separated list of test names to mark as `xfail`. These `xfail` tests are "strict", meaning that an unexpected pass with them causes a test failure, rather than a silent pass.
Some thoughts:
* Maybe it makes sense to support `fnmatch` syntax here, e.g. `test_signature_verify::*`?
Closes #87.
Closes #94.

action, conftest: initial xfail support

---

README.md
test/conftest.py

For #99
If you're only testing verification use-cases locally, you don't need the OIDC JWT.
You can test this change with:
```sh
(env) $ pytest test --skip-signing --entrypoint=SIGSTORE_CLIENT
```
* Enabled easier local testing for verification with `pytest test --skip-signing --entrypoint=SIGSTORE_CLIENT`
N/A

Make it easier to run verification test locally

---

test/client.py
test/test_bundle.py
test/test_certificate_verify.py
test/test_signature_verify.py

* Improved handling for the "unexpected success" case: print details like the command arguments  
* command arguments are now shown in a more useful form in error messages
---
An unexpected success now looks like this:
```
_____________________________ test_verify_rejects_invalid_inclusion_proof ______________________________
client = <test.client.SigstoreClient object at 0x7f842a9066d0>
make_materials_by_type = <function make_materials_by_type.<locals>._make_materials_by_type at 0x7f842a90c0e0>
def test_verify_rejects_invalid_inclusion_proof(
client: SigstoreClient, make_materials_by_type: _MakeMaterialsByType
) -> None:
"""
Check that the client rejects a bundle with an old inclusion proof
"""
materials: BundleMaterials
input_path, materials = make_materials_by_type("a.txt", …
```

Improve unexpected success handling

---

README.md
docs/cli_protocol.md
test/client.py
test/conftest.py
test/test_bundle.py

Closes #121 
One conformance requirement for the clients is that they should be able to run the commands against `staging`.  After this PR, the clients should be able to receive the `--staging` token in the command line and point to staging resources.
Updated client run function to receive `staging` argument.
Updated run subprocess call to pass `--staging` flag to clients cli when required.
Modified CLI parser to receive --staging flag
Update CLI and conformance READMEs adding staging features

feat:checking that the client is allowed to run against staging

---

sigstore-python-conformance

sigstore-python expects the order `sigstore [--staging] <subcmd>`.
This is part of #121

sigstore-python-conformance: Handle --staging

---

.github/workflows/conformance.yml
README.md
action.py
action.yml
test/conftest.py
test/test_signature_verify.py
test/test_simple.py

This might be enough to close #121.
Do several small changes required to support staging tests in self-test
* the `enable-staging` action input defaults to false: we may want to reconsider before releasing -- maybe opt-out is better?
* only a few tests are marked as compatible with staging at this point: I may have missed some but since there are loads of false negatives in the remaining tests (tests that seemingly have the correct result but only because they fail for the wrong reasons on staging) I didn't want to extend without research
* `--staging` flag is sort of  documented in cli_protocol.md but it could probably be improved 
Test run https://github.com/sigstore/sigstore-conformance/actions/runs/8017481217

Add staging to selftest

---

.github/workflows/conformance.yml
Makefile
README.md
action.py
action.yml
docs/cli_protocol.md
pyproject.toml
test/client.py

Main change here is the staging invocation: I'm proposing that a single action invocation only runs the testsuite once because 
* xfails becames painful if staging expected failures are not the same as prod (which seems like a normal thing at times).
* The test results are much clearer ("Staging conformance failure" is not as critical as "production conformance failure")
Other changes in this PR (from testing and reviewing for a hopefully near future release):
* run selftest daily (and on dispatch)
* update linter config to silence warnings
* update cli protocol doc and move `--staging` so it's not after the artifact filename
Fixes #130
I'll mark William a reviewer since we originally agreed to run test suite twice but  I think we may have been wrong.
--- 
For release Notes:
* The action …

Tweak staging invocation

---

requirements.txt

Bumps sigstore-protobuf-specs to `~= 0.3.0`, which includes v3 bundle support. Without this bump, anything in sigstore-python that constructs v3 bundles under the hood will fail (hooray for hidden version conflicts in Python environments!)

requirements: bump sigstore-protobuf-specs

---

.github/workflows/conformance.yml
Makefile
dev-requirements.txt
requirements.txt
test/test_bundle.py
test/test_signature_verify.py
test/test_simple.py

This has been out for a while, let's see if this breaks any of the automation.

dev-requirements: switch to sigstore-python 3.x

---

.github/workflows/conformance.yml
docs/cli_protocol.md
sigstore-python-conformance
test/client.py
test/conftest.py
test/test_bundle.py
test/test_simple.py

This PR adds support for verifying hashes (instead of files) to the CLI protocol (only when verifying bundles).
It also adapts the `sigstore-python-conformance` helper to support it, given `sigstore-python` supports verifying hashes [since v3.3.0](https://github.com/sigstore/sigstore-python/releases/tag/v3.3.0).
All the existing bundle verification tests have been parametrized to also test the hash verification, in addition to the existing `Path` (file) verification.
This closes https://github.com/sigstore/sigstore-conformance/issues/157
cc @woodruffw

Support verifying digests in addition to artifacts

---

action.yml
requirements.txt
setup/setup.bash
test/client.py
test/test_bundle.py

~~WIP.~~
This adds conformance suite tests for CPython's releases, which use Sigstore bundles. The idea is to continuously check whether CPython releases are verifiable by multiple clients.

Conformance tests for CPython release signatures

---

docs/cli_protocol.md
sigstore-python-conformance
test/client.py
test/test_bundle.py

fixes #161, this doesn't remove the feature developed in #158, only removes the `--verify-digest` flag instead making clients parse the argument to determine in the action.

Remove --verify-digest flag

---

action.yml

For the latest releases: https://github.com/woodruffw/cpython-release-tracker/pull/5
I need to figure out a good way to automate this PR as well.

action: bump cpython-release-tracker ref

---

action.yml

See https://github.com/woodruffw/cpython-release-tracker/pull/7.

Bump cpython artifacts

---

test/test_bundle.py

This should make local use slightly less painful, since users won't need to do workarounds like `GITHUB_WORKSPACE=/tmp` to have these skip properly.
A larger refactor here would be to allow users to configure this path wholly, so that people can also easily run the CPython bundle tests locally.
CC @bdehamer

test: don't assume GITHUB_WORKSPACE

---

.github/workflows/conformance.yml
action.yml
test/test_bundle.py

This adds an input that allows the (hefty) CPython release bundle tests to be outright skipped. It also adds a selftest matrix configuration to ensure the input works as expected.

add skip-cpython-release-tests

---

test/test_bundle.py

~~WIP; still root causing the failure that surfaced this.~~
This checks both `x509_certificate_chain` and `certificate` in the `test_sign_does_not_produce_root` test, since clients can place bundled certificates in either (and as of v3 bundles, are required to use the latter instead of the former).
xref https://github.com/sigstore/sigstore-go/actions/runs/12697653217
CC @haydentherapper

handle different certificate fields correctly

---

.github/dependabot.yml
requirements.txt

Purpose here is to make the test suite reproducible for action users (test suite dependency updates should not break workflows). At the moment I believe the action is broken for everyone except sigstore-python and the selftest here...
* Pin dependencies by exact version
* Setup dependabot: update once a month
Fixes #178, but I will file another issue about installing sigstore-python in a virtual env of its own

Pin dependencies, setup dependabot

---

action.py

Configure pytest to always print test durations per https://github.com/sigstore/sigstore-conformance/issues/188#issuecomment-2610145491.
NONE
NONE

Always show test durations

---

test/test_bundle.py

This should improve performance by a lot but should not affect coverage (since all artifacts in one release are likely very similar).
Changes in the PR:
* non-sigstore signed cpython releases are not counted as subtests (this likely did not affect performance in any way but seems like a better way to count)
* only one artifact per cpython release is tested
We're left with 70 cpython release tests (down from 1633). The selftest runtime went from 330 seconds to 90 seconds, I think sigstore-java will get even more benefit from this.

cpython verify: Only verify one artifact per release

---

action.yml
setup/setup.bash

* This makes sure we don't pollute the main Python environment which is good for at least sigstore-python in https://github.com/sigstore/sigstore-python/pull/1276
* I'm sure there are neater ways to handle this but this seems to work: The client-under-test and the test suite can now successfully use different sigstore-protobuf-specs versions

Install dependencies in a virtualenv in the action too

---

README.md

Changelog is
* Use current sigstore-protobuf-specs
* Make sure the test suite is installed in a separate environment in both Makefile and the action
--- 
This release is a little debatable: it contains very little that is useful for other users but it does fix bugs that affect sigstore-python (blocks sigstore/sigstore-python#1276)
The alternative to this release is that we use a non-released conformance in sigstore-python for now and remember to update later: https://github.com/jku/sigstore-python/commit/e28b7656d40e0e28c05959e8aa8aff8e3d367ee6
@woodruffw  @loosebazooka  I can do the release tag here but am fine either way if you have opinions.

Prepare for 0.0.18 release

---

docs/cli_protocol.md
sigstore-python-conformance
test/assets/rekor2_signing_config.json
test/assets/rekor2_trusted_root.json
test/client.py
test/conftest.py
test/test_bundle.py

Contents:
* Add `--signing-config` (and `--trusted-root`) to the client-under-test CLI when signing
* Make selftest client compatible with the new options
* Add a test that verifies clients capability to sign with rekor2 using the new flags
Background:
* We don't really want to use .e.g. `--staging` to test for specific results since we know the expected result changes over time (e.g. recommended tlog to use changes from rekor1 to rekor2)
* Instead we want to provide a specific signingconfig and trustedroot so we know the expected result -- the downside of this is that the services themselves may be turned offline at some point: this signingconfig and trustedroot needs to be updated at that point
* verifying the resulting bundle with the selftest client should mean that the bundle is good …

Support --signing-config in CLI, test for rekor2 signing

---

Makefile

Current pip-tools and pip are compatible again
Fixes #211

makefile: Remove pip-tools workaround

---

action.yml
setup/setup.bash
sigstore-python-conformance

The signing test now uses selftest client to verify the resulting bundle (with the idea that the client itself might not have good enough verification support -- but selftest client should be tested well).
Make sure the selftest client is installed during action setup.
Fixes #247.
---

action setup: Install selftest client as well
