sigstore/sigstore-conformance

- docs/cli_protocol.md
- sigstore-python-conformance
- test/client.py
Signed-off-by: William Woodruff <william@trailofbits.com>
> cli_protocol: change `--certificate-email` to `--certificate-identity`

- README.md
I've added a bit more detail to the README to capture what we discussed in https://github.com/sigstore/cosign/issues/2434 in regards to what we aim to achieve with CLI testing as opposed a vector based approach.
CC: @znewman01
> README: Elaborate on what we aim to achieve with CLI testing

- .github/workflows/conformance.yml
- README.md
- action.yml
> Support conformance testing on third-party PRs

- action.yml
See https://github.com/sigstore/sigstore-python/pull/350#issuecomment-1358062994.
Signed-off-by: William Woodruff <william@trailofbits.com>
> action: restrict label check to third-party PRs

- README.md
`s/trailofbits/sigstore` in README
> Update README.md to reflect new github org

- .github/workflows/extremely-dangerous-oidc-broadcaster.yml
To emphasize that it must not be trusted.
CC @tetsuo-cpp @di
> Give the OIDC broadcaster a scary name

- action.py
- action.yml
- test/client.py
> Fix our use of `GITHUB_TOKEN`

- README.md
Let's get the OIDC beacon changes out now.
> README: prep 0.0.4

- Makefile
- README.md
- action.py
- test/conftest.py
Towards enabling local conformance testing, remove the required `--identity-token` CLI flag when executing via `pytest`.
> cli: move oidc token into pytest

- action.yml
- test/test_signature_verify.py
This is a follow-on to https://github.com/sigstore/sigstore-conformance/issues/81, to allow testing verification libraries that don't support signing. There was a test missed that uses signing, and a typo in getting the input from the Action to the test driver.
NONE
N/A
> Fix typo to reference `skip-signing` input; mark additional test as using signing

- README.md
Closes https://github.com/sigstore/sigstore-conformance/issues/103.
CC @jku
> README: prep 0.0.7

- README.md
> README: prep 0.0.8

- README.md
> README: prep 0.0.9

- README.md
> README: prep 0.0.10

- README.md
- dev-requirements.txt
- test/conftest.py
* Allow relative paths in --entrypoint
* Expand README with examples that run out-of-the-box
* Install sigstore in dev-requirements
Fixes #123
> Improve dev experience

- .gitignore
Running `make dev` previously created untracked files. Now they are ignored.
NONE
> Add a .gitignore based on sigstore-python

- .github/workflows/conformance.yml
should help determine quickly if failures are isolated to staging flakiness
> Isolate staging/production self tests from eachother

- test/conftest.py
- test/test_bundle.py
* Avoid variable reuse when variable type is different: this makes mypy happier
* include ruff automatic fixes
> Fix lint issues

- action.yml
- test/conftest.py
- test/test_simple.py
Add the "smarter" bit of https://github.com/sigstore/sigstore-conformance/pull/134, ensuring that sigstore implementations that are... slow... can still be tested
> Cache ID token only as long as it is valid

- README.md
Preps a release to get the recent local fixes out the door.
> README: prep 0.0.13

- README.md
So we can cut a 0.0.14 release
NONE
N/A
> Get ready for 0.0.14 release

- README.md
> Bump version in README for new release

- action.yml
See https://github.com/woodruffw/cpython-release-tracker/pull/18
> action: bump cpython-release-tracker

- README.md
> README: prep for v0.0.17 release

- README.md
I tagged the release already, this just updates the example
> README: Update version in example
